Ensure that Numpy is installed before it is referenced.
nikolasibalic/ARC-Alkali-Rydberg-Calculator pull request #115
Opened 2022-07-21 16:51 UTC by paul-romlow

When installing to an environment that does not have Numpy installed, the build fails. This waits to reference Numpy until after the setup_requires section has been resolved.

2022-07-22 09:25 UTC, nikolasibalic commented
HI @paul-romlow 

Thank you for contribution. I have just one question trying to understand use-case. Usually the dependencies that are needed are installed via `requirements.txt`.
This is done automatically when you do pip install. How did you do installation to run into this problem? Maybe you had some reason why you couldn't run pip install ?

2022-07-22 12:00 UTC, paul-romlow commented
We use Pants for a build system which creates a virtual environment first and then it builds the source (Linux, so no binary available) before installing all of the other requirements.
https://www.pantsbuild.org/

2022-08-22 17:18 UTC, paul-romlow commented
If this PR is not acceptable to you, would it be possible for you to publish a wheel (bdist_wheel) for amd64 Linux as is done with Windows and MacOS? I'd be happy to help with getting that set up, please let me know.

Thanks!

2022-08-23 07:44 UTC, nikolasibalic requested changes

2022-08-23 07:44 UTC, nikolasibalic commented on setup.py
> +    setup_requires=["numpy>=1.16.0"],
Can we change this to package named "oldest-supported-numpy" ?
That one will automatically pick oldest supported Numpy for corresponding Python version.
See [here](https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/issues/100#issuecomment-1036258981) for the reasons.
`setup_requires=["oldest-supported-numpy"],`

2022-08-23 07:45 UTC, nikolasibalic commented
@paul-romlow Please check if the above change is fine with you. If so, commit update, and I will accept this PR and release a new version.

2022-08-24 18:36 UTC, merged